version: '3'
services:
  backend:
    build: 
      context: backend/.
    restart : always
    ports:
      - "5000:5000"
    networks:
      - annet
  frontend: 
    build: 
      context: frontend/.
    ports: 
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - annet
networks:
  annet:


